# Promise // 11월 15일 (Mon)

### 자바스크립트는 비동기 처리를 위한 하나의 패턴으로 콜백함수를 사용한다. 하지만 전통적인 콜백 패턴은 콜백 헬로 인해 가독성이 나쁘고 비동거 처리 중 발생한 에러의 처리가 곤란하며 여러 개의 비동기 처리를 한번에 처리하는 데도 한계가 있다. ES6에서는 비동기 처리를 위한 하나의 또 다른 패턴으로 프로미스를 도입했다. 프로미스는 전통적인 콜백 패턴이 가진 단점을 보완하며 비동기 처리 시점을 명확하게 표현할 수 있다는 장점이 있다.

## 비동기 처리를 위한 콜백 패턴의 단점

#### 비동기 함수를 호출하면 함수 내부의 비동기로 동작하는 코드가 완료되지 않았다 해도 기다리지 않고 즉시 종료된다. 즉, 비동기 함수 내부의 비동기로 동작하는 코드는 비동기 함수가 종료된 이후에 완료된다. 따라서 비동기 함수 내부의 비동기로 동작하는 코드에서 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작하지 않는다.

#### 그러므로, 비동기 함수 처리 결과 (서버의 응답 등)에 대한 후속 처리는 비동기 함수 내부에서 수행해야 한다. 이때, 비동기 함수를 범용적으로 사용하기 위해 비동기 함수에 비동기 처리 결과에 대한 후속 처리를 수행하는 콜백 함수를 전달하는 것이 일반적이다. 비동기 처리가 성공하면 호출될 콜백 함수와 비동기 처리가 실패하면 호출될 콜백 함수를 전달할 수 있다.

### 비동기 처리를 위한 콜백 패턴의 문제점 중에서 가장 심각한 것은 에러 처리가 곤란하다는 것이다. 이를 위해 try, catch, finally 문을 사용해야 한다.

#### try, catch, finally 문은 에러 처리를 구현하는 방법이다.

```
try {
  const response = axios.get(URL);
} catch (error) {
  alert(error);
} finally {
  console.log("Done");
}
```

#### 먼저 try 코드 블럭이 실행된다. 이떄 try 코드 블럭내에서 에러가 발생하면 해당 에러는 catch 문의 error 변수에 할당이 되고 catch 코드 블럭이 실행되며 alert 함수가 실행된다. finally 코드 블럭은 에러 발생과 상관없이 반드시 한 번 실행된다. -> try, catch, finally문을 통해 에러를 처리하면 프로그램이 강제 종료되지 않는다는 장점이 있다.

## 프로미스의 생성

### Promise 생성자 함수를 new 연산자와 함께 호출하면 프로미스를 생성한다. Promise 생성자 함수는 비동기 처리를 수행할 콜백 함수를 인수로 전달 받는데 이 콜백 함수는 resolve와 reject 함수를 인수로 전달받는다.

```
const promise = new Promise((resolve, reject) => {
  // Promise 함수의 콜백함수는 내부에서 비동기 처리를 수행한다.
  if((/* 비동기 처리 성공 */) {
    resolve('result');
  } else { /* 비동기  처리 실패 */
    reject('failure reason');
  }
})
```

#### Promise 생성자 함수가 인수로 전달받은 콜백 함수 내부에서 비동기 처리를 수행한다. 이때 비동기 처리가 성공하면 콜백 함수의 인수로 전달받은 resolve 함수를 호출하고, 비동기 처리가 실패하면 reject 함수를 호출한다.

### 프로미스 상태정보

| 프로미스의 상태정보 | 의미                                  | 상태 변경 조건                   |
| ------------------- | ------------------------------------- | -------------------------------- |
| pending             | 비동기 처리가 아직 수행되지 않은 상태 | 프로미스가 생성된 직후 기본 상태 |
| fulfilled           | 비동기 처리가 수행된 상태(성공)       | resolve 함수 호출                |
| rejected            | 비동기 처리가 수행된 상태(실패)       | reject 함수 호출                 |

#### 비동기 처리 성공 : resolve 함수를 호출해 프로미스를 fulfilled 상태로 변경한다.

#### 비동기 처리 실패 : reject 함수를 호출해 프로미스를 rejected 상태로 변경한다.

## 프로미스의 후속 처리 메서드

### 프로미스의 비동기 처리 상태가 변화하면 이에 따른 후속 처리를 해야한다. 예를 들어, 프로미스가 fulfilled 상태가 되면 프로미스의 처리 결과를 가지고 무언가를 해야 하고, 프로미스가 rejected 상태가 되면 프로미스의 처리 결과(에러)를 가지고 에러 처리를 해야한다. 이를 위해 프로미스는 후속 메서드 then, catch, finally를 제공한다.

#### 프로미스의 비동기 처리 상태가 변화하면 후속 처리 메서드에 인수로 전달한 콜백 함수가 선택적으로 호출된다. 이 때 후속 처리 메서드의 콜백 함수에 프로미스의 처리 결과가 인수로 전달된다.

### Promise.prototype.then

#### then 메서드는 두 개의 콜백함수를 인수로 전달 받는다. 첫번째 콜백함수는 프로미스가 fulfilled 상태가 되면 호출, 두번째 콜백함수는 프로미스가 rejected 상태가 되면 호출

```
// fulfilled
new Promise(resolve => resolve('fulfilled')).then(v => console.log(v), e => console.error(e));

// rejected
new Promise((_, reject) => reject(new Error('rejected'))).then(v => console.log(v), e => console.log(e));
```

#### then 메서드는 언제나 프로미스를 반환한다. 만약 then 메서드의 콜백 함수가 프로미스를 반환하면 그 프로미스를 그대로 반환하고, 콜백 함수가 프로미스가 아닌 값을 반환하면 그 값을 암묵적으로 resolve 또는 reject하여 프로미스를 생성해 반환한다.

### Promise.prototype.catch

#### catch 메서드는 한 개의 콜백 함수를 인수로 전달받는다. catch 메서드의 콜백 함수는 프로미스가 rejected 상태인 경우만 호출된다.

```
// rejected
new Promise((_, reject) => reject(new Error('rejected'))).catch(e => console.log(e));
```
